[package]
name = "aoc-2020d5p2"
version = "0.1.0"
authors = ["Nathan Essex <nathan@essex.id.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
regex = "1.4.2"
anyhow = "1.0.34"
